"""
Django settings for notification project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$4ylr5-7o_0jzc#$ymnqa^=u2_kjvsmba9oor1e%bz^!2(viw6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    'message',
    # 'notifications',
    'webpush',
]
 

WEBPUSH_SETTINGS = {
   "VAPID_PUBLIC_KEY": "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxcTQvZDA2NitaMndSSENCRjNURApSUXJrYU4vK2gxUkhlMExoVThnSlZHSUN5YThGTlhOR0FHaERxNFR6TFNmTUJYYUFNK1JRWU9vd2xlN3ZWdHBvCllUMWcyVjNwV3ZCK25mY0NYRE5mUVB5S1BsWG5NSko0NDNDV0lING9mSHppdEJmVFBRcGFDTU9leUpRN3VPQnUKV09pL1R0ZDBTTThPbHVGR1NxeHhTRUJ0MmZLVVA2SjZJZXRQR0lxSnQyTHB1SWlrbmxtazdZbzhya3Z1cEQ4eAp2ZlFjMnd1MkFJSzc4dThOZ0tBTUpLVFM1OGdPWTROUGNKSVJST1NRMk13SW9ZRm9kTEF5eVJsS1BoNTRRTDVmCks5enorVGpxbG85TTJOeTEvTWpXNng0dVVYQ0JJZGUzUlJPc2NIZHRZRDJ2WkpZaXZ5VnVTazIwZXplQmVLWEIKN3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg",
   "VAPID_PRIVATE_KEY": "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQ3FyajkzVHJyNW5iQkUKY0lFWGRNTkZDdVJvMy82SFZFZDdRdUZUeUFsVVlnTEpyd1UxYzBZQWFFT3JoUE10Sjh3RmRvQXo1RkJnNmpDVgo3dTlXMm1oaFBXRFpYZWxhOEg2ZDl3SmNNMTlBL0lvK1ZlY3drbmpqY0pZZ2ZpaDhmT0swRjlNOUNsb0l3NTdJCmxEdTQ0RzVZNkw5TzEzUkl6dzZXNFVaS3JIRklRRzNaOHBRL29ub2g2MDhZaW9tM1l1bTRpS1NlV2FUdGlqeXUKUys2a1B6Rzk5QnpiQzdZQWdydnk3dzJBb0F3a3BOTG55QTVqZzA5d2toRkU1SkRZekFpaGdXaDBzRExKR1VvKwpIbmhBdmw4cjNQUDVPT3FXajB6WTNMWDh5TmJySGk1UmNJRWgxN2RGRTZ4d2QyMWdQYTlrbGlLL0pXNUtUYlI3Ck40RjRwY0h2QWdNQkFBRUNnZ0VBQ0daZG0rZzFXTkRqT3BCZTMySDd0T0RUQk9aTDNIL1AvM0pNZ2V4aVU5TjUKclB0VUY2RlRYSjhhVlhmMjVTTlptSENRaS8wOGgzTXB3NkhvQ0MrUGhpN3R5VVRQUUk1OWJNREVvNkpUbWNYVAo5K1ZsRDFybUN0WWc5L3NTMEZoRkZVcVJqQ1lxUllGN0d3YWw1SFN4enVaYXpwZlpQVGErSjd3YjB0T25Ha0J5Ck44M1VCTzlnTXY3bElvM3BrQ2VtUVFacCtMRU9YZ3ZLNEs0bkFMY1B2djdUMHFtMFo5MTBYTXAwVDhzMWVGbW0KVlY2Ryt1RndpbU1ydjZzYmhCa0hzamxvdEkwSWYvUGVwdWVaSThWZmE4MnVCK05PeUV2UVFPakRISVd0YmM4SwpjN2tnNm1jTnphRGxMZTRlc3dCTjhLbTUrUWdKaTB2ZDlpU3pIMDR4UVFLQmdRRGNUYTlRYmh2a2FLTEtqQTdKCmNaRS82YXlBakNHUU9yZ3ZSdTV2WFlWMWJjMndia2lSRk9XZzl1dHZma08xL1RTdTl2anRlTGxVMVJYaURQMHEKeFAzdmlPVG1xV29XTjZUZEVCMnU3V1pQbitQSzloWUdkWDZNcUpVWk1wVUVTYlJkd3ZIRHhieVpoQkZDUkt5SwphNXVjVzFwUW1SSWJDM1AyalNiYkxyTXh1UUtCZ1FER1ZpNDRFRlNMS2hBWndodkJSZFFlS285K29EWjJXQTlCCkFyNzlucmVWR1ZhUVNkTEdaWHlaRDE1dnk1UlRWT2lTZ1B4S0x6b1kvblU5NmpYaDljL3AyWTR6QWZTS1BBV0YKMUVzVEkycHU2VG9aYjlKMS9pWEVYVWcrN0cycGdQNFBhVWJQdEpUTmxsdWVBNzB2Um1sOHJxdXZOODBQNHFyZApuL2E2RkJVRTV3S0JnUUNFb0FmdzViakk4dTA5L3I5UUtweUUyNHBNQVJDYm9aNE1hQ2xXeGZoNFQxaEs1TG12CkRlT0gyZDYyeWs2OUd1aENoTkFyTmtoc2Q3T3EyS0w0d29zVlQxWnVQb050U0tacHB6QVhoVGZZcTZzWkhyajMKdm5nbStiNTQ0dWl2SWlnQllrRGwyUDdIZEtobk9xeWMwRmRuODk4Vk1uR2g4bTBuZXFadndWZURrUUtCZ1FDKwppYXg5VDdMb3Z0QVk3dEdiSzJwTVVMYnAveUJUTU9YMm5weTlLZTFUMzdPNWlqSmpScndjanhjNmIybGZaUUxKClBBRWpnNXRjeDVmNmt6YVFqWVhnTXBEWmo5ZE50YnZZaGNwWjZId25jUWZQeUExNExXQTY5U0tpMEovSlo1S3IKVzRnYm9uQVIwWkRTak9VQ3RiSkJoY3lKMkNHNFVSbTFNQ2ZuTzhPMW9RS0JnUUN6QmpXMWZoMFNwNmRGSTBiUQpQZGVPdU1NNlRZdVNBY1NHWHByZFBIRDdURThKNXpNUGs5K2V5NjBiMEVqU05aZGFqZWM3MmJTcEkyZGh2d3cxCnd1S2N0djQ3emVuNVBIMmpqRzI4cG9WcDd1SzdoT3ZaME13ZnVaS1lvbzNicmFvbmJyTnhrTDdDYytKNGRQbysKb0N1cE94YlpWdnVNWWp2WmtmMy9uZ3luQWc9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg",
   "VAPID_ADMIN_EMAIL": "ichandru2805@gmail.com"
}

AUTH_USER_MODEL = 'message.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'notification.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'message.context_processors.notifications_context',

            ],
        },
    },
]

WSGI_APPLICATION = 'notification.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]